### ISSUE TITLE
Request: Allow zero in `ID`, or opt back in to non-zero optimizations

### ISSUE THREAD

**Issue by callumbirks** [atolab/uhlc-rs#17]
In my project, which uses HLCs, a "client" will assign themselves a placeholder ID of 0 until they have been assigned an ID when syncing data with a remote server. Now that this crate's ID representation has changed from a `NonZeroU128` to a `[u8; 16]`, is there a reason that an ID with value 0 should be disallowed?
I skimmed through the code and couldn't find anything that would disallow 0, other that the `From`/`TryFrom` implementations for ID.

**Comment by callumbirks** [comment]
Or, if a 0-value is still disallowed, maybe could opt back in to non-zero compiler optimisations with something like:
```
struct ID {
    first: NonZeroU8,
    rest: [u8; 15],
}
```
I've tested that an `Option<ID>` is still size 16.

**Comment by callumbirks** [comment]
Is using `#[repr(packed)]` and changing the internal repr back to `NonZeroU128` a possibility? This makes the align 1, although @Mallets I'm not sure if this could be a problem for Zenoh. Would that break some requirements for you?

**Comment by Mallets** [comment]
Hello @callumbirks , both cases are not a possibility for UHLC and Zenoh:

1. Non-zero requirement is necessary for bijective string conversion that doesn't allow leading zeros
2. `NonZeroU128` is not so portable on different architecturs and platforms. It is also too much subject to layout changes from the compiler that can easily break Zenoh bindings

**Comment by callumbirks** [comment]
@Mallets Thanks for the response. That makes sense. I'll close this issue.
